version: '3'

volumes:
  local_postgres_data: {}


services:
  brunswick:
    depends_on:
      - mailhog
      - postgres
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./server:/app/server
      - ./db:/app/db
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000
      - 8000:8000
      - 8888:8888
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/brunswick_test
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - DEFAULT_HOST=0.0.0.0
    user: "1000:1000"
  postgres:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=brunswick_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    # user: "1000:1000"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"


  ###########################################
  #### Active if share project to client ####
  ###########################################

#  pagekite-web:
#    build:
#      context: .
#      dockerfile: ./compose/local/pagekite/Dockerfile
#    command: '--defaults --service_on=http:ebsa.esipascal.pagekite.me:ebsa:8000:test'
#  pagekite-email:
#    build:
#      context: .
#      dockerfile: ./compose/local/pagekite/Dockerfile
#    command: '--defaults --service_on=http:email.ebsa.esipascal.pagekite.me:mailhog:8025:test'
